### ISSUE TITLE
Getting error when i add morethan 9 menu items

### ISSUE THREAD

**Issue by Raviteja11122** [yako-dev/flutter-full-screen-menu#3]
```
════════ Exception caught by widgets library ═══════════════════════════════════════════════════════
The following RangeError was thrown building _OverlayEntry-[LabeledGlobalKey<_OverlayEntryState>#aeaa4](state: _OverlayEntryState#b4803):
RangeError (index): Invalid value: Not in range 0..8, inclusive: 9

The relevant error-causing widget was: 
  MaterialApp file:///home/tekfriday/AndroidStudioProjects/social_cards/lib/main.dart:49:12
When the exception was thrown, this was the stack: 
#0      List.[] (dart:core-patch/growable_array.dart:149:60)
#1      __TDBaseWidgetState.initState (package:full_screen_menu/src/widgets/full_screen_menu_base_widget.dart:47:42)
#2      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4355:58)
#3      ComponentElement.mount (package:flutter/src/widgets/framework.dart:4201:5)
#4      Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194:14)
```

**Comment by yadaniyil** [comment]
@Raviteja11122 sorry for delay.
Fixed in version `full_screen_menu: ^0.1.3`?
